var searchData=
[
  ['ubufaligned_0',['ubufAligned',['https://doc.qt.io/qt-6/qrhi.html#ubufAligned',1,'QRhi']]],
  ['ubufalignment_1',['ubufAlignment',['https://doc.qt.io/qt-6/qrhi.html#ubufAlignment',1,'QRhi']]],
  ['uilanguage_2',['uiLanguage',['https://doc.qt.io/qt-6/qjsengine.html#uiLanguage-prop',1,'QJSEngine']]],
  ['uilanguagechanged_3',['uiLanguageChanged',['https://doc.qt.io/qt-6/qjsengine.html#uiLanguage-prop',1,'QJSEngine']]],
  ['uilanguages_4',['uiLanguages',['https://doc.qt.io/qt-6/qlocale.html#uiLanguages',1,'QLocale']]],
  ['unblock_5',['unblock',['https://doc.qt.io/qt-6/qsignalblocker.html#unblock',1,'QSignalBlocker']]],
  ['uncompresseddata_6',['uncompressedData',['https://doc.qt.io/qt-6/qresource.html#uncompressedData',1,'QResource']]],
  ['uncompressedsize_7',['uncompressedSize',['https://doc.qt.io/qt-6/qresource.html#uncompressedSize',1,'QResource']]],
  ['underline_8',['underline',['https://doc.qt.io/qt-6/qfont.html#underline',1,'QFont::underline()'],['https://doc.qt.io/qt-6/qglyphrun.html#underline',1,'QGlyphRun::underline()']]],
  ['underlinecolor_9',['underlineColor',['https://doc.qt.io/qt-6/qtextcharformat.html#underlineColor',1,'QTextCharFormat']]],
  ['underlinepos_10',['underlinepos',['https://doc.qt.io/qt-6/qfontmetrics.html#underlinePos',1,'QFontMetrics::underlinePos()'],['https://doc.qt.io/qt-6/qfontmetricsf.html#underlinePos',1,'QFontMetricsF::underlinePos()']]],
  ['underlineposition_11',['underlinePosition',['https://doc.qt.io/qt-6/qrawfont.html#underlinePosition',1,'QRawFont']]],
  ['underlinestyle_12',['underlineStyle',['https://doc.qt.io/qt-6/qtextcharformat.html#underlineStyle',1,'QTextCharFormat']]],
  ['underlyingtype_13',['underlyingType',['https://doc.qt.io/qt-6/qmetatype.html#underlyingType',1,'QMetaType']]],
  ['undo_14',['undo',['https://doc.qt.io/qt-6/qtextdocument.html#undo-1',1,'QTextDocument::undo()'],['https://doc.qt.io/qt-6/qtextdocument.html#undo',1,'QTextDocument::undo(QTextCursor *cursor)'],['https://doc.qt.io/qt-6/qundocommand.html#undo',1,'QUndoCommand::undo()'],['https://doc.qt.io/qt-6/qundogroup.html#undo',1,'QUndoGroup::undo()'],['https://doc.qt.io/qt-6/qundostack.html#undo',1,'QUndoStack::undo()'],['https://doc.qt.io/qt-6/qml-qtquick-textedit.html#undo-method',1,'QtQuick.TextEdit::undo()'],['https://doc.qt.io/qt-6/qml-qtquick-textinput.html#undo-method',1,'QtQuick.TextInput::undo()']]],
  ['undoavailable_15',['undoAvailable',['https://doc.qt.io/qt-6/qtextdocument.html#undoAvailable',1,'QTextDocument']]],
  ['undocommandadded_16',['undoCommandAdded',['https://doc.qt.io/qt-6/qtextdocument.html#undoCommandAdded',1,'QTextDocument']]],
  ['undolimit_17',['undoLimit',['https://doc.qt.io/qt-6/qundostack.html#undoLimit-prop',1,'QUndoStack']]],
  ['undotext_18',['undotext',['https://doc.qt.io/qt-6/qundogroup.html#undoText',1,'QUndoGroup::undoText()'],['https://doc.qt.io/qt-6/qundostack.html#undoText',1,'QUndoStack::undoText()']]],
  ['undotextchanged_19',['undotextchanged',['https://doc.qt.io/qt-6/qundogroup.html#undoTextChanged',1,'QUndoGroup::undoTextChanged()'],['https://doc.qt.io/qt-6/qundostack.html#undoTextChanged',1,'QUndoStack::undoTextChanged()']]],
  ['unfreeze_20',['unfreeze',['https://doc.qt.io/qt-6/qml-qtquick-particles-itemparticle.html#unfreeze-method',1,'QtQuick.Particles.ItemParticle']]],
  ['ungetchar_21',['ungetChar',['https://doc.qt.io/qt-6/qiodevice.html#ungetChar',1,'QIODevice']]],
  ['ungrabmouse_22',['ungrabMouse',['https://doc.qt.io/qt-6/qquickitem-obsolete.html#ungrabMouse',1,'QQuickItem']]],
  ['ungrabtouchpoints_23',['ungrabTouchPoints',['https://doc.qt.io/qt-6/qquickitem-obsolete.html#ungrabTouchPoints',1,'QQuickItem']]],
  ['unicode_24',['unicode',['https://doc.qt.io/qt-6/qlatin1char.html#unicode',1,'QLatin1Char::unicode()'],['https://doc.qt.io/qt-6/qstring.html#unicode',1,'QString::unicode()'],['https://doc.qt.io/qt-6/qchar.html#unicode-1',1,'QChar::unicode() const const'],['https://doc.qt.io/qt-6/qchar.html#unicode',1,'QChar::unicode()']]],
  ['unicodeversion_25',['unicodeversion',['https://doc.qt.io/qt-6/qchar.html#unicodeVersion-1',1,'QChar::unicodeVersion(char32_t ucs4)'],['https://doc.qt.io/qt-6/qchar.html#unicodeVersion',1,'QChar::unicodeVersion() const const']]],
  ['uniformblocks_26',['uniformBlocks',['https://doc.qt.io/qt-6/qshaderdescription.html#uniformBlocks',1,'QShaderDescription']]],
  ['uniformbuffer_27',['uniformbuffer',['https://doc.qt.io/qt-6/qrhishaderresourcebinding.html#uniformBuffer',1,'QRhiShaderResourceBinding::uniformBuffer(int binding, QRhiShaderResourceBinding::StageFlags stage, QRhiBuffer *buf)'],['https://doc.qt.io/qt-6/qrhishaderresourcebinding.html#uniformBuffer-1',1,'QRhiShaderResourceBinding::uniformBuffer(int binding, QRhiShaderResourceBinding::StageFlags stage, QRhiBuffer *buf, quint32 offset, quint32 size)']]],
  ['uniformbufferwithdynamicoffset_28',['uniformBufferWithDynamicOffset',['https://doc.qt.io/qt-6/qrhishaderresourcebinding.html#uniformBufferWithDynamicOffset',1,'QRhiShaderResourceBinding']]],
  ['uniformdata_29',['uniformData',['https://doc.qt.io/qt-6/qsgmaterialshader-renderstate.html#uniformData',1,'QSGMaterialShader::RenderState']]],
  ['uniqueid_30',['uniqueid',['https://doc.qt.io/qt-6/qtabletevent-obsolete.html#uniqueId',1,'QTabletEvent::uniqueId()'],['https://doc.qt.io/qt-6/qpointingdevice.html#uniqueId',1,'QPointingDevice::uniqueId()'],['https://doc.qt.io/qt-6/qaccessible.html#uniqueId',1,'QAccessible::uniqueId()'],['https://doc.qt.io/qt-6/qeventpoint.html#uniqueId-prop',1,'QEventPoint::uniqueId()']]],
  ['uniquekeys_31',['uniquekeys',['https://doc.qt.io/qt-6/qmultimap.html#uniqueKeys',1,'QMultiMap::uniqueKeys()'],['https://doc.qt.io/qt-6/qmultihash.html#uniqueKeys',1,'QMultiHash::uniqueKeys() const const']]],
  ['unite_32',['unite',['https://doc.qt.io/qt-6/qmultihash.html#unite',1,'QMultiHash::unite(const QHash&lt; Key, T &gt; &amp;other)'],['https://doc.qt.io/qt-6/qmultihash.html#unite-1',1,'QMultiHash::unite(const QMultiHash&lt; Key, T &gt; &amp;other)'],['https://doc.qt.io/qt-6/qmultimap.html#unite',1,'QMultiMap::unite(QMultiMap&lt; Key, T &gt; &amp;&amp;other)'],['https://doc.qt.io/qt-6/qmultimap.html#unite-1',1,'QMultiMap::unite(const QMultiMap&lt; Key, T &gt; &amp;other)'],['https://doc.qt.io/qt-6/qset.html#unite',1,'QSet::unite()']]],
  ['united_33',['united',['https://doc.qt.io/qt-6/qpolygonf.html#united',1,'QPolygonF::united()'],['https://doc.qt.io/qt-6/qregion.html#united-1',1,'QRegion::united(const QRegion &amp;r) const const'],['https://doc.qt.io/qt-6/qregion.html#united',1,'QRegion::united(const QRect &amp;rect) const const'],['https://doc.qt.io/qt-6/qpolygon.html#united',1,'QPolygon::united()'],['https://doc.qt.io/qt-6/qpainterpath.html#united',1,'QPainterPath::united()'],['https://doc.qt.io/qt-6/qrectf.html#united',1,'QRectF::united()'],['https://doc.qt.io/qt-6/qrect.html#united',1,'QRect::united()']]],
  ['units_34',['units',['https://doc.qt.io/qt-6/qpagelayout.html#units',1,'QPageLayout']]],
  ['unitsperem_35',['unitsPerEm',['https://doc.qt.io/qt-6/qrawfont.html#unitsPerEm',1,'QRawFont']]],
  ['unitvector_36',['unitVector',['https://doc.qt.io/qt-6/qlinef.html#unitVector',1,'QLineF']]],
  ['unixprocessparameters_37',['unixProcessParameters',['https://doc.qt.io/qt-6/qprocess.html#unixProcessParameters',1,'QProcess']]],
  ['unknownoptionnames_38',['unknownOptionNames',['https://doc.qt.io/qt-6/qcommandlineparser.html#unknownOptionNames',1,'QCommandLineParser']]],
  ['unload_39',['unload',['https://doc.qt.io/qt-6/qlibrary.html#unload',1,'QLibrary::unload()'],['https://doc.qt.io/qt-6/qpluginloader.html#unload',1,'QPluginLoader::unload()']]],
  ['unloadimage_40',['unloadImage',['https://doc.qt.io/qt-6/qml-qtquick-canvas.html#unloadImage-method',1,'QtQuick.Canvas']]],
  ['unlock_41',['unlock',['https://doc.qt.io/qt-6/qmutex.html#unlock',1,'QMutex::unlock()'],['https://doc.qt.io/qt-6/qmutexlocker.html#unlock',1,'QMutexLocker::unlock()'],['https://doc.qt.io/qt-6/qreadlocker.html#unlock',1,'QReadLocker::unlock()'],['https://doc.qt.io/qt-6/qreadwritelock.html#unlock',1,'QReadWriteLock::unlock()'],['https://doc.qt.io/qt-6/qrecursivemutex.html#unlock',1,'QRecursiveMutex::unlock()'],['https://doc.qt.io/qt-6/qsharedmemory.html#unlock',1,'QSharedMemory::unlock()'],['https://doc.qt.io/qt-6/qwritelocker.html#unlock',1,'QWriteLocker::unlock()'],['https://doc.qt.io/qt-6/qlockfile.html#unlock',1,'QLockFile::unlock()']]],
  ['unmap_42',['unmap',['https://doc.qt.io/qt-6/qfiledevice.html#unmap',1,'QFileDevice']]],
  ['unpremultiplied_43',['unpremultiplied',['https://doc.qt.io/qt-6/qrgba64.html#unpremultiplied',1,'QRgba64::unpremultiplied()'],['https://doc.qt.io/qt-6/qrgbafloat.html#unpremultiplied',1,'QRgbaFloat::unpremultiplied()']]],
  ['unproject_44',['unproject',['https://doc.qt.io/qt-6/qvector3d.html#unproject',1,'QVector3D']]],
  ['unregisterhandler_45',['unregisterHandler',['https://doc.qt.io/qt-6/qabstracttextdocumentlayout.html#unregisterHandler',1,'QAbstractTextDocumentLayout']]],
  ['unregisterresource_46',['unregisterresource',['https://doc.qt.io/qt-6/qresource.html#unregisterResource',1,'QResource::unregisterResource(const QString &amp;rccFileName, const QString &amp;mapRoot)'],['https://doc.qt.io/qt-6/qresource.html#unregisterResource-1',1,'QResource::unregisterResource(const uchar *rccData, const QString &amp;mapRoot)']]],
  ['unregistersocketnotifier_47',['unregisterSocketNotifier',['https://doc.qt.io/qt-6/qabstracteventdispatcher.html#unregisterSocketNotifier',1,'QAbstractEventDispatcher']]],
  ['unregistertimer_48',['unregistertimer',['https://doc.qt.io/qt-6/qabstracteventdispatcher.html#unregisterTimer',1,'QAbstractEventDispatcher::unregisterTimer(Qt::TimerId timerId)'],['https://doc.qt.io/qt-6/qabstracteventdispatcher.html#unregisterTimer-1',1,'QAbstractEventDispatcher::unregisterTimer(int timerId)=0']]],
  ['unregistertimers_49',['unregisterTimers',['https://doc.qt.io/qt-6/qabstracteventdispatcher.html#unregisterTimers',1,'QAbstractEventDispatcher']]],
  ['unregistertypes_50',['unregisterTypes',['https://doc.qt.io/qt-6/qqmlextensionplugin.html#unregisterTypes',1,'QQmlExtensionPlugin']]],
  ['unselect_51',['unselect',['https://doc.qt.io/qt-6/qaccessibleselectioninterface.html#unselect',1,'QAccessibleSelectionInterface']]],
  ['unselectcolumn_52',['unselectColumn',['https://doc.qt.io/qt-6/qaccessibletableinterface.html#unselectColumn',1,'QAccessibleTableInterface']]],
  ['unselectrow_53',['unselectRow',['https://doc.qt.io/qt-6/qaccessibletableinterface.html#unselectRow',1,'QAccessibleTableInterface']]],
  ['unsetcolorscheme_54',['unsetColorScheme',['https://doc.qt.io/qt-6/qstylehints.html#unsetColorScheme',1,'QStyleHints']]],
  ['unsetcursor_55',['unsetcursor',['https://doc.qt.io/qt-6/qwindow.html#unsetCursor',1,'QWindow::unsetCursor()'],['https://doc.qt.io/qt-6/qquickitem.html#unsetCursor',1,'QQuickItem::unsetCursor()']]],
  ['unseterror_56',['unsetError',['https://doc.qt.io/qt-6/qfiledevice.html#unsetError',1,'QFileDevice']]],
  ['unsetfeature_57',['unsetFeature',['https://doc.qt.io/qt-6/qfont.html#unsetFeature',1,'QFont']]],
  ['unseturlhandler_58',['unsetUrlHandler',['https://doc.qt.io/qt-6/qdesktopservices.html#unsetUrlHandler',1,'QDesktopServices']]],
  ['unsetvariableaxis_59',['unsetVariableAxis',['https://doc.qt.io/qt-6/qfont.html#unsetVariableAxis',1,'QFont']]],
  ['unwrap_60',['unwrap',['https://doc.qt.io/qt-6/qfuture.html#unwrap',1,'QFuture']]],
  ['update_61',['update',['https://doc.qt.io/qt-6/qpaintdevicewindow.html#update-2',1,'QPaintDeviceWindow::update()'],['https://doc.qt.io/qt-6/qquickwindow.html#update',1,'QQuickWindow::update()'],['https://doc.qt.io/qt-6/qquickrhiitemrenderer.html#update',1,'QQuickRhiItemRenderer::update()'],['https://doc.qt.io/qt-6/qquickpainteditem.html#update',1,'QQuickPaintedItem::update()'],['https://doc.qt.io/qt-6/qquickitem.html#update',1,'QQuickItem::update()'],['https://doc.qt.io/qt-6/qquickframebufferobject-renderer.html#update',1,'QQuickFramebufferObject::Renderer::update()'],['https://doc.qt.io/qt-6/qpaintdevicewindow.html#update-1',1,'QPaintDeviceWindow::update(const QRect &amp;rect)'],['https://doc.qt.io/qt-6/qpaintdevicewindow.html#update',1,'QPaintDeviceWindow::update()'],['https://doc.qt.io/qt-6/qinputmethod.html#update',1,'QInputMethod::update()'],['https://doc.qt.io/qt-6/qabstracttextdocumentlayout.html#update',1,'QAbstractTextDocumentLayout::update()']]],
  ['updateaccessibility_62',['updateAccessibility',['https://doc.qt.io/qt-6/qaccessible.html#updateAccessibility',1,'QAccessible']]],
  ['updateblock_63',['updateBlock',['https://doc.qt.io/qt-6/qabstracttextdocumentlayout.html#updateBlock',1,'QAbstractTextDocumentLayout']]],
  ['updatecoloredrectgeometry_64',['updateColoredRectGeometry',['https://doc.qt.io/qt-6/qsggeometry.html#updateColoredRectGeometry',1,'QSGGeometry']]],
  ['updatecurrenttime_65',['updatecurrenttime',['https://doc.qt.io/qt-6/qparallelanimationgroup.html#updateCurrentTime',1,'QParallelAnimationGroup::updateCurrentTime()'],['https://doc.qt.io/qt-6/qvariantanimation.html#updateCurrentTime',1,'QVariantAnimation::updateCurrentTime()'],['https://doc.qt.io/qt-6/qsequentialanimationgroup.html#updateCurrentTime',1,'QSequentialAnimationGroup::updateCurrentTime()'],['https://doc.qt.io/qt-6/qpauseanimation.html#updateCurrentTime',1,'QPauseAnimation::updateCurrentTime()'],['https://doc.qt.io/qt-6/qabstractanimation.html#updateCurrentTime',1,'QAbstractAnimation::updateCurrentTime()']]],
  ['updatecurrentvalue_66',['updatecurrentvalue',['https://doc.qt.io/qt-6/qvariantanimation.html#updateCurrentValue',1,'QVariantAnimation::updateCurrentValue()'],['https://doc.qt.io/qt-6/qpropertyanimation.html#updateCurrentValue',1,'QPropertyAnimation::updateCurrentValue()']]],
  ['updated_67',['updated',['https://doc.qt.io/qt-6/qmovie.html#updated',1,'QMovie::updated()'],['https://doc.qt.io/qt-6/qml-qtquick-multipointtoucharea.html#updated-signal',1,'QtQuick.MultiPointTouchArea::updated()']]],
  ['updatedirection_68',['updatedirection',['https://doc.qt.io/qt-6/qabstractanimation.html#updateDirection',1,'QAbstractAnimation::updateDirection()'],['https://doc.qt.io/qt-6/qparallelanimationgroup.html#updateDirection',1,'QParallelAnimationGroup::updateDirection()'],['https://doc.qt.io/qt-6/qsequentialanimationgroup.html#updateDirection',1,'QSequentialAnimationGroup::updateDirection()']]],
  ['updatedynamicbuffer_69',['updateDynamicBuffer',['https://doc.qt.io/qt-6/qrhiresourceupdatebatch.html#updateDynamicBuffer',1,'QRhiResourceUpdateBatch']]],
  ['updategraphicspipelinestate_70',['updateGraphicsPipelineState',['https://doc.qt.io/qt-6/qsgmaterialshader.html#updateGraphicsPipelineState',1,'QSGMaterialShader']]],
  ['updateinputmethod_71',['updateInputMethod',['https://doc.qt.io/qt-6/qquickitem.html#updateInputMethod',1,'QQuickItem']]],
  ['updateinterval_72',['updateInterval',['https://doc.qt.io/qt-6/qtimeline.html#updateInterval-prop',1,'QTimeLine']]],
  ['updatepaintnode_73',['updatepaintnode',['https://doc.qt.io/qt-6/qquickitem.html#updatePaintNode',1,'QQuickItem::updatePaintNode()'],['https://doc.qt.io/qt-6/qquickpainteditem.html#updatePaintNode',1,'QQuickPaintedItem::updatePaintNode()']]],
  ['updatepolish_74',['updatePolish',['https://doc.qt.io/qt-6/qquickitem.html#updatePolish',1,'QQuickItem']]],
  ['updaterectgeometry_75',['updateRectGeometry',['https://doc.qt.io/qt-6/qsggeometry.html#updateRectGeometry',1,'QSGGeometry']]],
  ['updatesampledimage_76',['updateSampledImage',['https://doc.qt.io/qt-6/qsgmaterialshader.html#updateSampledImage',1,'QSGMaterialShader']]],
  ['updatestate_77',['updatestate',['https://doc.qt.io/qt-6/qsequentialanimationgroup.html#updateState',1,'QSequentialAnimationGroup::updateState()'],['https://doc.qt.io/qt-6/qpaintengine.html#updateState',1,'QPaintEngine::updateState()'],['https://doc.qt.io/qt-6/qvariantanimation.html#updateState',1,'QVariantAnimation::updateState()'],['https://doc.qt.io/qt-6/qparallelanimationgroup.html#updateState',1,'QParallelAnimationGroup::updateState()'],['https://doc.qt.io/qt-6/qabstractanimation.html#updateState',1,'QAbstractAnimation::updateState()'],['https://doc.qt.io/qt-6/qpropertyanimation.html#updateState',1,'QPropertyAnimation::updateState()']]],
  ['updateswapchainproxydata_78',['updateSwapChainProxyData',['https://doc.qt.io/qt-6/qrhi.html#updateSwapChainProxyData',1,'QRhi']]],
  ['updatetexture_79',['updateTexture',['https://doc.qt.io/qt-6/qsgdynamictexture.html#updateTexture',1,'QSGDynamicTexture']]],
  ['updatetexturedrectgeometry_80',['updateTexturedRectGeometry',['https://doc.qt.io/qt-6/qsggeometry.html#updateTexturedRectGeometry',1,'QSGGeometry']]],
  ['updateuniformdata_81',['updateUniformData',['https://doc.qt.io/qt-6/qsgmaterialshader.html#updateUniformData',1,'QSGMaterialShader']]],
  ['updatevalue_82',['updateValue',['https://doc.qt.io/qt-6/qqmlpropertymap.html#updateValue',1,'QQmlPropertyMap']]],
  ['uploadstaticbuffer_83',['uploadstaticbuffer',['https://doc.qt.io/qt-6/qrhiresourceupdatebatch.html#uploadStaticBuffer',1,'QRhiResourceUpdateBatch::uploadStaticBuffer(QRhiBuffer *buf, quint32 offset, quint32 size, const void *data)'],['https://doc.qt.io/qt-6/qrhiresourceupdatebatch.html#uploadStaticBuffer-1',1,'QRhiResourceUpdateBatch::uploadStaticBuffer(QRhiBuffer *buf, const void *data)']]],
  ['uploadtexture_84',['uploadtexture',['https://doc.qt.io/qt-6/qrhiresourceupdatebatch.html#uploadTexture',1,'QRhiResourceUpdateBatch::uploadTexture(QRhiTexture *tex, const QImage &amp;image)'],['https://doc.qt.io/qt-6/qrhiresourceupdatebatch.html#uploadTexture-1',1,'QRhiResourceUpdateBatch::uploadTexture(QRhiTexture *tex, const QRhiTextureUploadDescription &amp;desc)']]],
  ['upperbound_85',['upperbound',['https://doc.qt.io/qt-6/qmap.html#upperBound',1,'QMap::upperBound(const Key &amp;key)'],['https://doc.qt.io/qt-6/qmap.html#upperBound-1',1,'QMap::upperBound(const Key &amp;key) const const'],['https://doc.qt.io/qt-6/qmultimap.html#upperBound',1,'QMultiMap::upperBound(const Key &amp;key)'],['https://doc.qt.io/qt-6/qmultimap.html#upperBound-1',1,'QMultiMap::upperBound(const Key &amp;key) const const']]],
  ['uppercasebase_86',['uppercasebase',['https://doc.qt.io/qt-6/qt.html#uppercasebase',1,'Qt']]],
  ['uppercasedigits_87',['uppercasedigits',['https://doc.qt.io/qt-6/qt.html#uppercasedigits',1,'Qt']]],
  ['uppressed_88',['upPressed',['https://doc.qt.io/qt-6/qml-qtquick-keys.html#upPressed-signal',1,'QtQuick.Keys']]],
  ['url_89',['url',['https://doc.qt.io/qt-6/qqmlcomponent.html#url-prop',1,'QQmlComponent::url()'],['https://doc.qt.io/qt-6/qurl.html#url',1,'QUrl::url()'],['https://doc.qt.io/qt-6/qquickitemgrabresult.html#url-prop',1,'QQuickItemGrabResult::url()'],['https://doc.qt.io/qt-6/qml-qtqml-qt.html#url-method',1,'QtQml.Qt::url()'],['https://doc.qt.io/qt-6/qfileopenevent.html#url',1,'QFileOpenEvent::url()'],['https://doc.qt.io/qt-6/qqmlerror.html#url',1,'QQmlError::url()']]],
  ['urlinterceptors_90',['urlInterceptors',['https://doc.qt.io/qt-6/qqmlengine.html#urlInterceptors',1,'QQmlEngine']]],
  ['urls_91',['urls',['https://doc.qt.io/qt-6/qmimedata.html#urls',1,'QMimeData']]],
  ['urltolocalfileorqrc_92',['urltolocalfileorqrc',['https://doc.qt.io/qt-6/qqmlfile.html#urlToLocalFileOrQrc-1',1,'QQmlFile::urlToLocalFileOrQrc(const QUrl &amp;url)'],['https://doc.qt.io/qt-6/qqmlfile.html#urlToLocalFileOrQrc',1,'QQmlFile::urlToLocalFileOrQrc(const QString &amp;url)']]],
  ['usage_93',['usage',['https://doc.qt.io/qt-6/qrhibuffer.html#usage',1,'QRhiBuffer']]],
  ['usedesignmetrics_94',['usedesignmetrics',['https://doc.qt.io/qt-6/qtextdocument.html#useDesignMetrics-prop',1,'QTextDocument::useDesignMetrics()'],['https://doc.qt.io/qt-6/qtextoption.html#useDesignMetrics',1,'QTextOption::useDesignMetrics()']]],
  ['usehovereffects_95',['useHoverEffects',['https://doc.qt.io/qt-6/qstylehints.html#useHoverEffects-prop',1,'QStyleHints']]],
  ['usehovereffectschanged_96',['useHoverEffectsChanged',['https://doc.qt.io/qt-6/qstylehints.html#useHoverEffects-prop',1,'QStyleHints']]],
  ['userdata_97',['userData',['https://doc.qt.io/qt-6/qtextblock.html#userData',1,'QTextBlock']]],
  ['userinfo_98',['userInfo',['https://doc.qt.io/qt-6/qurl.html#userInfo',1,'QUrl']]],
  ['username_99',['userName',['https://doc.qt.io/qt-6/qurl.html#userName',1,'QUrl']]],
  ['userproperty_100',['userProperty',['https://doc.qt.io/qt-6/qmetaobject.html#userProperty',1,'QMetaObject']]],
  ['userstate_101',['userState',['https://doc.qt.io/qt-6/qtextblock.html#userState',1,'QTextBlock']]],
  ['usertlextensions_102',['useRtlExtensions',['https://doc.qt.io/qt-6/qstylehints.html#useRtlExtensions-prop',1,'QStyleHints']]],
  ['usertype_103',['usertype',['https://doc.qt.io/qt-6/qmetaproperty.html#userType',1,'QMetaProperty::userType()'],['https://doc.qt.io/qt-6/qvariant.html#userType',1,'QVariant::userType()']]],
  ['usleep_104',['usleep',['https://doc.qt.io/qt-6/qthread.html#usleep',1,'QThread']]],
  ['utc_105',['utc',['https://doc.qt.io/qt-6/qtimezone.html#utc',1,'QTimeZone']]],
  ['utf16_106',['utf16',['https://doc.qt.io/qt-6/qstring.html#utf16',1,'QString::utf16()'],['https://doc.qt.io/qt-6/qstringview.html#utf16',1,'QStringView::utf16()']]],
  ['utf8_107',['utf8',['https://doc.qt.io/qt-6/qutf8stringview.html#utf8',1,'QUtf8StringView']]],
  ['utiformime_108',['utiForMime',['https://doc.qt.io/qt-6/qutimimeconverter.html#utiForMime',1,'QUtiMimeConverter']]]
];
