var searchData=
[
  ['tabfocusbehavior_0',['tabFocusBehavior',['https://doc.qt.io/qt-6/qstylehints.html#tabFocusBehavior-prop',1,'QStyleHints']]],
  ['targetobject_1',['targetObject',['https://doc.qt.io/qt-6/qpropertyanimation.html#targetObject-prop',1,'QPropertyAnimation']]],
  ['text_2',['text',['https://doc.qt.io/qt-6/qaction.html#text-prop',1,'QAction']]],
  ['texturefollowsitemsize_3',['textureFollowsItemSize',['https://doc.qt.io/qt-6/qquickframebufferobject.html#textureFollowsItemSize-prop',1,'QQuickFramebufferObject']]],
  ['texturesize_4',['textureSize',['https://doc.qt.io/qt-6/qquickpainteditem.html#textureSize-prop',1,'QQuickPaintedItem']]],
  ['textwidth_5',['textWidth',['https://doc.qt.io/qt-6/qtextdocument.html#textWidth-prop',1,'QTextDocument']]],
  ['threadpriority_6',['threadPriority',['https://doc.qt.io/qt-6/qthreadpool.html#threadPriority-prop',1,'QThreadPool']]],
  ['timeheld_7',['timeHeld',['https://doc.qt.io/qt-6/qeventpoint.html#timeHeld-prop',1,'QEventPoint']]],
  ['timertype_8',['timertype',['https://doc.qt.io/qt-6/qtimer.html#timerType-prop',1,'QTimer::timerType'],['https://doc.qt.io/qt-6/qchronotimer.html#timerType-prop',1,'QChronoTimer::timerType']]],
  ['timestamp_9',['timestamp',['https://doc.qt.io/qt-6/qeventpoint.html#timestamp-prop',1,'QEventPoint']]],
  ['title_10',['title',['https://doc.qt.io/qt-6/qwindow.html#title-prop',1,'QWindow']]],
  ['tooltip_11',['toolTip',['https://doc.qt.io/qt-6/qaction.html#toolTip-prop',1,'QAction']]],
  ['top_12',['top',['https://doc.qt.io/qt-6/qdoublevalidator.html#top-prop',1,'QDoubleValidator::top'],['https://doc.qt.io/qt-6/qintvalidator.html#top-prop',1,'QIntValidator::top']]],
  ['touchdoubletapdistance_13',['touchDoubleTapDistance',['https://doc.qt.io/qt-6/qstylehints.html#touchDoubleTapDistance-prop',1,'QStyleHints']]],
  ['transformorigin_14',['transformOrigin',['https://doc.qt.io/qt-6/qquickitem.html#transformOrigin-prop',1,'QQuickItem']]],
  ['transientparent_15',['transientparent',['https://doc.qt.io/qt-6/qwindow.html#transientParent-prop',1,'QWindow::transientParent'],['https://doc.qt.io/qt-6/qquickwindow.html#transientParent-prop',1,'QQuickWindow::transientParent']]]
];
